### ISSUE TITLE
Upgrade of system-upgrade-controller fails

### ISSUE THREAD

**Issue by ariep** [nimbolus/helm-charts#17]
Upgrading releases of `system-upgrade-controller` from the previous version `0.3.1` to the new `0.4.0` consistently fails with this error:
```
Helm upgrade failed for release system-upgrade/system-upgrade-controller with chart system-upgrade-controller@0.4.0: cannot patch "system-upgrade" with kind ClusterRoleBinding: ClusterRoleBinding.rbac.authorization.k8s.io "system-upgrade" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"system-upgrade-controller"}: cannot change roleRef
```

I'm not sure if your goal is to make such upgrades possible. If so, this is a bug. If not, it would be good to at least mark this as a potentially breaking change in the changelog or release notes.

**Comment by lu1as** [comment]
Thanks for reporting this issue. Upgrading should definitely be supported. Fix will be merged soon.
